# analysis_options.yaml

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Dinonaktifkan karena terlalu ketat untuk proyek ini
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    cascade_invocations: false
    prefer_expression_function_bodies: false
    always_use_package_imports: false
    avoid_print: false
    do_not_use_environment: false
